"use client";

import Link from "next/link";
import { useState } from "react";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { Accordion, AccordionDetails, AccordionSummary, Alert, Avatar, Box, Button, Chip, Container, Dialog, DialogContent, DialogTitle, Grid, Paper, Stack, Typography } from "@mui/material";
import { RsvpForm } from "@/components/rsvp/RsvpForm";
import type { RegistrationFieldDefinition } from "@/components/rsvp/registrationTypes";

type Props = { orgSlug: string; preview: boolean; event: { slug: string; title: string; coverImageUrl: string | null; location: string; isOnline: boolean; status: string; start: string; end: string; timezone: string; capacity: number | null }; page: { tagline: string; logoUrl: string | null; accentColor: string | null; aboutHtml: string; sections: Array<{ type: string; isVisible: boolean }> }; highlights: Array<{ id: string; title: string; description: string }>; sessions: Array<{ id: string; slug: string; title: string; start: string; type: string; room: string | null; speakers: Array<{ slug: string; name: string }> }>; speakers: Array<{ id: string; slug: string; name: string; photoUrl: string | null; websiteUrl: string | null; headline: string; organisation: string }>; sponsors: Array<{ id: string; name: string; logoUrl: string | null; description: string; websiteUrl: string | null; tier: string }>; venue: { location: string; mapLinkUrl: string | null } | null; faqs: Array<{ id: string; question: string; answerHtml: string }>; resources: Array<{ id: string; title: string; description: string; href: string }>; registrationFields: RegistrationFieldDefinition[]; confirmedCount: number | null };

const fmt = (value: string, zone: string) => new Date(value).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: zone });
const titleSx = { fontSize: { xs: "2rem", md: "2.5rem" }, mb: 2 };
function Rich({ html }: { html: string }) { return html ? <Box sx={{ "& p": { lineHeight: 1.8, my: 0 }, "& a": { color: "primary.main" } }} dangerouslySetInnerHTML={{ __html: html }} /> : null; }

export function EventWebsiteShell(p: Props) {
  const [open, setOpen] = useState(false);
  const [shared, setShared] = useState(false);
  const shown = new Set(p.page.sections.filter((x) => x.isVisible).map((x) => x.type));
  const accent = p.page.accentColor || "primary.main";
  const section = (type: string, child: React.ReactNode) => shown.has(type) ? <Box component="section" sx={{ py: { xs: 3.5, md: 5 } }}>{child}</Box> : null;
  const share = async () => { try { if (navigator.share) await navigator.share({ title: p.event.title, url: location.href }); else await navigator.clipboard.writeText(location.href); setShared(true); } catch { /* sharing cancelled */ } };
  return <Box sx={{ minHeight: "100vh", bgcolor: "background.default", pb: 6 }}>
    {p.preview ? <Alert severity="info" sx={{ borderRadius: 0 }}>Preview mode — only authorized organizers can see draft content.</Alert> : null}
    <Container maxWidth="lg" sx={{ pt: { xs: 2, sm: 3 } }}>
      <Box sx={{ bgcolor: accent, color: "primary.contrastText", borderRadius: { xs: 3, md: 5 }, overflow: "hidden", boxShadow: "0 18px 48px rgba(0,0,0,0.14)" }}>
        <Grid container>
          <Grid size={{ xs: 12, md: 7 }}><Stack spacing={2.25} sx={{ p: { xs: 3, sm: 5, md: 6 }, minHeight: { md: 430 }, justifyContent: "center" }}>
            {p.page.logoUrl ? <Avatar src={p.page.logoUrl} alt="" variant="rounded" sx={{ width: 68, height: 68, bgcolor: "rgba(255,255,255,0.16)" }} /> : null}
            <Box><Typography variant="h1" sx={{ fontSize: { xs: "2.35rem", sm: "3.5rem", md: "4.25rem" }, lineHeight: 0.98, letterSpacing: "-0.045em", fontWeight: 800 }}>{p.event.title}</Typography>{p.page.tagline ? <Typography variant="h6" sx={{ mt: 2, opacity: 0.9, fontWeight: 400 }}>{p.page.tagline}</Typography> : null}</Box>
            <Stack spacing={0.5} sx={{ fontSize: { xs: "1rem", sm: "1.125rem" }, opacity: 0.95 }}><Typography>{fmt(p.event.start, p.event.timezone)} – {fmt(p.event.end, p.event.timezone)}</Typography><Typography>{p.event.isOnline ? "Online event" : p.event.location}</Typography></Stack>
            <Stack direction="row" spacing={1} useFlexGap sx={{ flexWrap: "wrap" }}>{p.sessions.length > 0 ? <Chip label={`${p.sessions.length} session${p.sessions.length === 1 ? "" : "s"}`} size="small" sx={{ bgcolor: "rgba(255,255,255,0.14)", color: "inherit" }} /> : null}{p.speakers.length > 0 ? <Chip label={`${p.speakers.length} speaker${p.speakers.length === 1 ? "" : "s"}`} size="small" sx={{ bgcolor: "rgba(255,255,255,0.14)", color: "inherit" }} /> : null}</Stack>
          </Stack></Grid>
          <Grid size={{ xs: 12, md: 5 }} sx={{ display: "flex", alignItems: "center", p: { xs: 2, sm: 3, md: 4 }, bgcolor: "rgba(0,0,0,0.08)" }}><Paper elevation={0} sx={{ p: { xs: 2.5, sm: 3 }, width: "100%", borderRadius: 3 }}><Typography variant="h5" sx={{ fontWeight: 750, mb: 1 }}>Join this event</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2.5 }}>Reserve your free place in a few moments.</Typography>{p.event.status === "CANCELLED" ? <Alert severity="error">Event cancelled</Alert> : <Button variant="contained" size="large" fullWidth onClick={() => setOpen(true)}>Register now</Button>}{p.event.capacity != null && p.confirmedCount != null ? <Typography variant="body2" color="text.secondary" sx={{ mt: 2, textAlign: "center" }}>{p.confirmedCount} registered · {p.event.capacity - p.confirmedCount > 0 ? `${p.event.capacity - p.confirmedCount} places left` : "at capacity"}</Typography> : null}<Button onClick={share} variant="text" fullWidth sx={{ mt: 1.5 }}>{shared ? "Link copied" : "Share event"}</Button></Paper></Grid>
        </Grid>
      </Box>
    </Container>
    <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm" aria-labelledby="event-registration-title"><DialogTitle id="event-registration-title">Register for {p.event.title}</DialogTitle><DialogContent><Box sx={{ pt: 1 }}><RsvpForm orgSlug={p.orgSlug} eventSlug={p.event.slug} registrationFields={p.registrationFields} /></Box></DialogContent></Dialog>
    <Container maxWidth="lg">
      {section("ABOUT", <Paper variant="outlined" sx={{ p: { xs: 2.5, md: 4 }, borderRadius: 3 }}><Typography variant="h3" sx={titleSx}>About</Typography><Rich html={p.page.aboutHtml} /></Paper>)}
      {section("HIGHLIGHTS", p.highlights.length > 0 ? <><Typography variant="h3" sx={titleSx}>Highlights</Typography><Grid container spacing={2}>{p.highlights.map((x) => <Grid key={x.id} size={{ xs: 12, sm: 6, md: 4 }}><Paper variant="outlined" sx={{ p: 2.5, height: "100%", borderRadius: 3 }}><Typography sx={{ fontWeight: 750, mb: 0.75 }}>{x.title}</Typography>{x.description ? <Typography variant="body2" color="text.secondary">{x.description}</Typography> : null}</Paper></Grid>)}</Grid></> : null)}
      {section("SCHEDULE", p.sessions.length > 0 ? <><Typography variant="h3" sx={titleSx}>Programme</Typography><Stack spacing={1.25}>{p.sessions.map((x) => <Paper key={x.id} component={Link} href={`/${p.orgSlug}/${p.event.slug}/sessions/${x.slug}`} variant="outlined" sx={{ p: { xs: 2, sm: 2.5 }, color: "text.primary", textDecoration: "none", borderRadius: 3, transition: "0.2s", "&:hover": { borderColor: "primary.main", transform: "translateY(-1px)" } }}><Typography sx={{ fontWeight: 750 }}>{x.title}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>{fmt(x.start, p.event.timezone)} · {x.room || "Room TBA"} · {x.type}</Typography></Paper>)}</Stack></> : null)}
      {section("SPEAKERS", p.speakers.length > 0 ? <><Typography variant="h3" sx={titleSx}>Speakers</Typography><Grid container spacing={2}>{p.speakers.map((x) => <Grid key={x.id} size={{ xs: 12, sm: 6, md: 4 }}><Stack component={Link} href={x.websiteUrl || `/${p.orgSlug}/${p.event.slug}/speakers/${x.slug}`} target={x.websiteUrl ? "_blank" : undefined} rel={x.websiteUrl ? "noopener noreferrer" : undefined} direction="row" spacing={1.5} sx={{ color: "text.primary", textDecoration: "none", alignItems: "center" }}><Avatar src={x.photoUrl || undefined} alt="" sx={{ width: 64, height: 64 }} /><Box><Typography sx={{ fontWeight: 750 }}>{x.name}</Typography><Typography variant="body2" color="text.secondary">{[x.headline, x.organisation].filter(Boolean).join(" · ")}</Typography></Box></Stack></Grid>)}</Grid></> : null)}
      {section("SPONSORS", p.sponsors.length > 0 ? <><Typography variant="h3" sx={titleSx}>Sponsors & partners</Typography><Grid container spacing={2}>{p.sponsors.map((x) => <Grid key={x.id} size={{ xs: 12, sm: 6, md: 4 }}><Paper component={x.websiteUrl ? "a" : "div"} href={x.websiteUrl || undefined} target="_blank" rel="noreferrer" variant="outlined" sx={{ p: 2, height: "100%", color: "text.primary", textDecoration: "none", borderRadius: 3, transition: "0.2s", "&:hover": x.websiteUrl ? { borderColor: "primary.main", transform: "translateY(-1px)" } : undefined }}><Box sx={{ height: 104, p: 1.5, bgcolor: "#fff", borderRadius: 2, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden" }}>{x.logoUrl ? <Box component="img" src={x.logoUrl} alt={x.name} sx={{ width: "100%", height: "100%", objectFit: "contain", display: "block" }} /> : <Typography sx={{ color: "#171717", fontWeight: 750, textAlign: "center" }}>{x.name}</Typography>}</Box><Typography sx={{ fontWeight: 750, mt: 1.5 }}>{x.name}</Typography><Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 0.25 }}>{x.tier.replaceAll("_", " ")}</Typography>{x.description ? <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>{x.description}</Typography> : null}</Paper></Grid>)}</Grid></> : null)}
      {section("VENUE", p.venue ? <Paper variant="outlined" sx={{ p: { xs: 2.5, md: 4 }, borderRadius: 3 }}><Typography variant="h3" sx={titleSx}>Venue</Typography>{p.venue.location ? <Typography sx={{ fontWeight: 750 }}>{p.venue.location}</Typography> : null}{p.venue.mapLinkUrl ? <Button component="a" href={p.venue.mapLinkUrl} target="_blank" rel="noreferrer" variant="outlined" size="small" sx={{ mt: 2 }}>Open map</Button> : null}</Paper> : null)}
      {section("FAQ", p.faqs.length > 0 ? <><Typography variant="h3" sx={titleSx}>Frequently asked questions</Typography><Stack spacing={1}>{p.faqs.map((x) => <Accordion key={x.id} disableGutters elevation={0} sx={{ border: 1, borderColor: "divider", borderRadius: "12px !important", "&::before": { display: "none" } }}><AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls={`faq-${x.id}-content`} id={`faq-${x.id}-header`}><Typography sx={{ fontWeight: 750 }}>{x.question}</Typography></AccordionSummary><AccordionDetails id={`faq-${x.id}-content`}><Rich html={x.answerHtml} /></AccordionDetails></Accordion>)}</Stack></> : null)}
      {section("RESOURCES", p.resources.length > 0 ? <><Typography variant="h3" sx={titleSx}>Resources</Typography><Stack spacing={1.25}>{p.resources.map((x) => <Paper key={x.id} component="a" href={x.href} target="_blank" rel="noreferrer" variant="outlined" sx={{ p: 2.25, color: "text.primary", textDecoration: "none", borderRadius: 3 }}><Typography sx={{ fontWeight: 750 }}>{x.title}</Typography><Typography variant="body2" color="text.secondary">{x.description}</Typography></Paper>)}</Stack></> : null)}
    </Container>
  </Box>;
}
