import { notFound } from "next/navigation";
import Link from "next/link";
import Avatar from "@mui/material/Avatar";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { ContentVisibility } from "@prisma/client";
import { prisma } from "@/lib/db";
import { resolvePublicEventAccess } from "@/lib/publicEventAccess";
import { sanitizeRichText } from "@/lib/richText";

export default async function SpeakerPage({ params }: { params: Promise<{ orgSlug: string; eventSlug: string; speakerSlug: string }> }) { const { orgSlug, eventSlug, speakerSlug } = await params; const org = await prisma.organisation.findUnique({ where: { slug: orgSlug } }); if (!org) notFound(); const event = await prisma.event.findUnique({ where: { organisationId_slug: { organisationId: org.id, slug: eventSlug } }, include: { page: { select: { isPublished: true } } } }); if (!event) notFound(); const access = await resolvePublicEventAccess({ organisationId: org.id, eventId: event.id, status: event.status, privacyType: event.privacyType, websiteReleased: event.page?.isPublished ?? false }); if (!access.allowed) notFound(); const speaker = await prisma.eventSpeaker.findFirst({ where: { eventId: event.id, slug: speakerSlug, visibility: ContentVisibility.PUBLISHED }, include: { sessions: { include: { session: true } } } }); if (!speaker) notFound(); return <Stack spacing={2} sx={{ maxWidth: 800, py: 4 }}><Typography component={Link} href={`/${org.slug}/${event.slug}`} color="primary">{event.title}</Typography><Avatar src={speaker.photoUrl || undefined} alt="" sx={{ width: 120, height: 120 }} /><Typography variant="h3">{speaker.name}</Typography><Typography color="text.secondary">{[speaker.headline, speaker.organisation].filter(Boolean).join(" · ")}</Typography><Typography component="div" dangerouslySetInnerHTML={{ __html: sanitizeRichText(speaker.bioHtml) }} />{speaker.websiteUrl ? <Typography component="a" href={speaker.websiteUrl} target="_blank" rel="noreferrer">Website</Typography> : null}<Typography variant="h5">Sessions</Typography>{speaker.sessions.filter((x) => x.session.visibility === ContentVisibility.PUBLISHED).map(({ session }) => <Typography key={session.id} component={Link} href={`/${org.slug}/${event.slug}/sessions/${session.slug}`}>{session.title}</Typography>)}</Stack>; }
